version: '3.8'

services:
  # Our PostgreSQL database
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_pass
      POSTGRES_DB: blog_app
    ports:
      - "5432:5432"

  # Database management interface
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"
